const quotes = [
    "On victory, you deserve beer, in defeat, you need it",
    "Give me a woman who loves beer and I will conquer the world",
    "Let no man thirst for good beer",
    "Fermentation may have been a greater discovery than fire",
    "He was a wise man who invented beer",
    "The mouth of a perfectly happy man is filled with beer",
    "Many battles have been fought and won by soldiers nourished on beer",
    "Beer is proof that God loves us and wants us to be happy",
    "Most people hate the taste of beer to begin with. It is, however, a prejudice",
    "I’ve only been in love with a beer bottle and a mirror",
    "Beauty is in the eye of the beer holder",
    "24 hours in a day, 24 beers in a case. Coincidence?",
    "A man who lies about beer makes enemies",
    "For a quart of Ale is a meal for a King",
    "Beer’s intellectual. What a shame so many idiots drink it",
    "Beer makes you feel the way you ought to feel without beer",
    "They who drink beer will think beer",
    "Beer may not solve your problems, but neither will water or milk",
    "Alcohol, the cause and solution to all of life’s problems",
    "Beer: So much more than just a breakfast drink",
    "Homer no function beer well without",
    "I think getting drunk is the key to flying comfortably",
    "Milk is for babies. When you grow up you have to drink beer",
    "It looks good, it tastes good, and by golly it does you good.",
];
export default quotes;
